### ISSUE TITLE
Add NCBI taxon ID to APS scrape?

### ISSUE THREAD

**Issue by austinmeier** [jhpoelen/samara#24]
Is it possible to search the pathogens and hosts that have been scraped from APSnet against the NCBI taxonomy and return the NCBITaxonID in the scraped file?

**Comment by jhpoelen** [comment]
@austinmeier shouldn't be too hard to do. In fact, GloBI has done the linkages already after first pass at https://github.com/jhpoelen/eol-globi-data/issues/242 . You can find the NCBI linkages by running some [custom cypher query](http://neo4j.globalbioticinteractions.org/webadmin/#/data/search/START%20study%20%3D%20node%3Astudies('*%3A*')%0Awhere%20study.source%20%3D~%20'.*apsnet.*'%0Awith%20study%0Amatch%20study-%5B%3ACOLLECTED%5D-pathogen-%5B%3APATHOGEN_OF%5D-%3Ehost-%5B%3ACLASSIFIED_AS%5D-%3EhostTaxon%2C%20pathogen-%5B%3ACLASSIFIED_AS%5D-%3EpathogenTaxon%2C%20pathogenTaxon-%5B%3ASAME_AS*0..1%5D-%3EpTaxon%2C%20hostTaxon-%5B%3ASAME_AS*0..1%5D-%3EhTaxon%0Awhere%20has(pTaxon.externalId)%20AND%20pTaxon.externalId%20%3D~%20'NCBI.*'%20AND%20%0Ahas(hTaxon.externalId)%20AND%20hTaxon.externalId%20%3D~%20'NCBI.*'%20%0Areturn%20pTaxon.name%2C%20pTaxon.externalId%2C%20hTaxon.name%2C%20hTaxon.externalId%20limit%2010/). For screenshot, see attached. GloBI has integrated with http://resolver.globalames.org . Note however, that [an open #243 issue](https://github.com/jhpoelen/eol-globi-data/issues/243) may add some interesting name matches hits to the mix.

![screen shot 2016-08-05 at 3 59 36 pm](https://cloud.githubusercontent.com/assets/1084872/17452621/ad605764-5b25-11e6-9049-5f51624ec428.png)

Hoping to hear back from @dimus so we can decide to use alternate name resolver instead of global names.

**Comment by jhpoelen** [comment]
Added taxon mapping using GloBI taxon map. Issues with this taxon map should be reported https://github.com/jhpoelen/eol-globi-data .
